### PR TITLE
Support VolumeDriver.List

### PR DESCRIPTION
**Pull request by sarum90**
(Original title: Set Err in the success case to "" instead of None)

We recently did this in flocker as part of getting ready for docker 1.10, I'm guessing it has to be done here as well:

https://github.com/ClusterHQ/flocker/pull/2481

### CODE REVIEW

**Comment by sarum90** [comment]
Note: This is currently untested (I should really start a VM and install the release candidate and try using dvol to verify it's broken).  Putting it out there in case I don't get around to trying that, it does break, and someone happens to come across this and it speeds up their process.

**Comment by sarum90** [comment]
This appears to not be needed, just grabbed the nightly build from: https://master.dockerproject.org/

```
marcus_ewert@mewert-snapshot-test:~$ docker run -it --rm --volume-driver=dvol -v mvol1:/path busybox /bin/sh -c 'echo "hihi" > /path/vol'
marcus_ewert@mewert-snapshot-test:~$ cat /var/lib/dvol/volumes/mvol1/running_point/vol 
hihi
marcus_ewert@mewert-snapshot-test:~$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.10.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local dvol
 Network: host bridge null
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.72 GiB
Name: mewert-snapshot-test
ID: 3QJL:35Z3:JIT6:NOXT:T7NC:6XJQ:KGKE:B6KE:HILE:HZ6S:ML5H:MUZ7
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
marcus_ewert@mewert-snapshot-test:~$ docker --version
Docker version 1.10.0-dev, build 34a83f9
marcus_ewert@mewert-snapshot-test:~$ 
```

**Comment by sarum90** [comment]
Although we might need something for:
```
marcus_ewert@mewert-snapshot-test:~$ docker volume ls
list dvol: VolumeDriver.List: 
<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>No such child resource.</p>
  </body>
</html>
DRIVER              VOLUME NAME
local               9c31b493b7cc122b391948e4a0e79d6fd91b37247292c058455583659df28427
marcus_ewert@mewert-snapshot-test:~$
```

**Comment by lukemarsden** [comment]
Current output:
```
luke@slim:~$ docker volume ls
list dvol: VolumeDriver.List: 
<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>No such child resource.</p>
  </body>
</html>

DRIVER              VOLUME NAME
local               0356fb24c8fade752d46cff67e3542072619c867933e14260aff4e4fd0b48b1a
dvol                foo
```

ie it shows errors but doesn't actually stop it working

**Comment by lukemarsden** [comment]
@sarum90 fancy having a crack at this?

**Comment by sarum90** [comment]
Oh sure :)

**Comment by robhaswell** [comment]
This is now implemented in the Go version, so this branch has been superseded - sorry! Thank you anyway.

**Pull request closed without merging**
