### PR TITLE
[VOL-87] Docker volumes removed

### PR DESCRIPTION
**Pull request by robhaswell**
https://clusterhq.atlassian.net/browse/VOL-87

Branched off https://github.com/ClusterHQ/dvol/pull/42 (review #42 first).

(Oops this had the wrong branch name.)

This test asserts that dvol removes Docker volumes by:

1. Start a container with a named volume
2. Delete that volume with dvol
3. Start a new container with the named volume

Docker attempts to start the container but receives an error because the volume has been removed.

### CODE REVIEW

**Comment by lukemarsden** [comment]
Why is the python version is failing?

**Comment by robhaswell** [comment]
I don't know why this is failing on Travis yet passing on my laptop. Could the reviewer test it themselves please?

**Comment by lukemarsden** [comment]
I've reviewed this via `git diff origin/docker-containers-stopped-started-VOL-84...origin/docker-volumes-removed-87` and it LGTM. Please merge once #42 is merged. Thanks!

**Comment by robhaswell** [comment]
```

Luke Marsden [1:14 PM] 
ah, yes

[1:15] 
yes, hmm. well, i'm not very interested in fixing that in the python version.

Rob Haswell [1:15 PM] 
no

Luke Marsden [1:15 PM] 
but i would like to fix it in the go version.

[1:15] 
but tests need to pass on your local dev environment

Rob Haswell [1:15 PM] 
my advice would just to @skip_if_python the whole test

Luke Marsden [1:16 PM] 
yeah  ok

Rob Haswell [1:16 PM] 
factually it doesn’t work in Python so there is no point in trying to match its behaviour

Luke Marsden [1:16 PM] 
@skip_if_python
@skip_if_go :simple_smile:

Rob Haswell [1:16 PM] 
:simple_smile:

Luke Marsden [1:16 PM] 
then we can remove @skip_if_go later

[1:16] 
that's fine by me

[1:17] 
ie, feel free to land it like that
```

**Pull request merged**
